---
- name: ----- pulling image -----
  docker_image:
        name: centos
        source: pull
        # build, local, ...
  tags: centos_image

- name: ----- pulling image -----
  docker_image:
        name: nginx
        source: pull
  tags: nginx_image

- name: ----- build docker image -----
  docker_image:
        name: myimage:v3
        build:
          path: /home/myimage
          pull: yes
        source: build
  tags: build_image

- name: ----- inspect -----
  docker_image_info:
        name: centos
  register: inspect_out
  tags: inspect

- name: ----- show inspect out -----
  debug:
        msg: '{{inspect_out}}'
  tags: inspect

- name: ----- run a container -----
  docker_container:
        name: mynginx
        image: nginx
        ports:
                - '80:80'
  tags: run-con

- name: ----- container inspect -----
  docker_container_info:
        name: mynginx
  register: inspect_out
  tags: ins_con

- name: ----- msg of above -----
  debug:
        msg: '{{inspect_out}}'
  tags: ins_con

- name: ----- create a docker network -----
  docker_network:
        name: ansi_net
        driver: bridge
        ipam_config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1
            iprange: 192.168.10.0/25
  tags: doc_net
