- name: ----- TestDir Directory -----
  file:
    path: /home/TestDir
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [create_directory]

- name: ----- shell module -----
  shell: echo "test shell module" > TestFile
  args:
    chdir: /home/TestDir
  tags: [shell_mod_1]

- name: ----- df -h by shell mod -----
  shell: df -h
  tags: [shell_mod_2]

- name: ----- Raw mod -----
  raw: echo "test raw module" >> /home/TestDir/TestFile
  tags: [raw_mod]