- name: ----- TestDir Directory -----
  file:
    path: /home/TestDir
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [create_directory]

- name: ----- shell module -----
  shell: echo "test shell module" > TestFile
  args:
    chdir: /home/TestDir
  tags: [shell_mod]