- name: ----- Create /home/ansible/ -----
  file:
    path: /home/ansible
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [create_directory]

  - name: ----- Create /home/ansible/playbook-structure-1/ -----
    file:
      path: /home/ansible/playbook-structure-1
      state: directory
      owner: root
      group: root
      mode: 0755
    tags: [create_directory]
