- name: ----- reboot module -----
  reboot:
    reboot_timeout: 50
  tags: [reboot_mod]

- name: ----- mail module -----
  mail:
    host: 127.0.0.1
    port: 2025
    subject: Ansible-report
    body: Hello, this is an e-mail. I hope you like it ;-)
    from: amir@example.net (Amir Borzouie)
    to: John Doe <j.d@example.org>, Suzie Something <sue@example.com>
    cc: Charlie Root <root@localhost>
    attach: /etc/group /tmp/pavatar2.png
    headers: 'Reply-To=john@example.com|X-Special="Something or other"'
    charset: utf8
  delegate_to: localhost
  # As ansible delegate_to is a directive, not an individual module,
  # It integrates with other modules and it controls the task execution by 
  # deciding which host should run the task at runtime. 
  # ... this is a simple delegation where the control of execution 
  # transferred from remote host to the master.

- name: ----- subversion module -----
  subversion:
    repo: svn+ssh://an.example.org/path/to/repo
    dest: /srv/checkout
    username: amir
    password: 123
    checkout: no
    update: no
    revision: 5
  tags: [svn_mod]

- name: ----- get_url module -----
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    timeout: 30
    url_username: test
    url_password: test
  tags: [get_url_mod]

- name: ----- timezone module -----
  timezone:
    name: Asia/Tokyo
  tags: [timezone_mod]

- name: ----- iptables module -----
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: ens34
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 8600
    comment: Redirect web traffic to port 8600
  become: yes

- name: ----- mattermost module -----
  mattermost:
    url: http://mattermost.example.com
    api_key: my_api_key
    text: '{{ inventory_hostname }} completed'
    channel: notifications
    username: 'Ansible on {{ inventory_hostname }}'
    icon_url: http://www.example.com/some-image-file.png
  tags: [mattermost_mod]

- name: ----- git module -----
  git:
    repo: 'https://foosball.example.org/path/to/repo.git'
    dest: /srv/checkout
    version: release-0.22
  tags: [git_mod]

- name: ----- rsync module -----
  synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: "{{ inventory_hostname }}"

