# - name: ----- zypper_repository module -----
#   zypper_repository:
#     name: 
#     repo: 
#     state:
#   tags: [zypper_repository_mod]

# - name: ----- zypper module -----
#   zypper:
#     name: ''
#     state:
#     disable_gpg_check:
#   tags: [zypper_mod]

# - name: ----- yum_repository module -----
#   yum_repository:
#     name: 
#     description:
#     baseurl:
#     gpgcheck:
#     enabled:
#     state:
#   tags: [yum_repository_mod]

- name: ----- yum mod -----
  yum:
    name: httpd
    state: present
  tags: [yum_install]

- name: ----- yum list -----
  yum:
    list: httpd
  register: yum_list_out
  tags: [yum_list]

- name: ----- show yum list -----
  debug: 
    msg: "{{yum_list_out}}"
  tags: [yum_list]

- name: ----- yum latest for just security updates -----
  yum:
    name: httpd
    state: latest
    security: yes
    bugfix: yes
  tags: [yum_latest]

- name: ----- apt module -----
  apt:
    name: nginx
    state: present
  tags: [apt_mod]

- name: ----- install a .deb package -----
  apt:
    deb: /opt/package.deb
  tags: [apt_.deb_installation]