- name: ----- Template module -----
  template: # template can be used to replace config files on remote hosts
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    backup: yes
    force: yes
  tags: [template_mod]