- name: ----- Group module -----
  group:
    name: devops
    state: present
  tags: [group_mod]

- name: ----- User module -----
  user:
    name: userx
    group: devops
    state: present
    shell: /bin/bash
    password: 1234
  tags: [user_mod]