- name: ----- Lineinfile Module -----
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '        listen       8082;'
  # insertbefore:
    line: '   listen  8080 default_server;'
  tags: [lineinfile_mod]

- name: ----- Lineinfile Remove line -----
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: absent
    regexp: '^   listen'
  tags: [lineinfile_remove_line]